# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true

- task: Yarn@3
  inputs:
    arguments: 'install'

- task: Yarn@3
  inputs:
    arguments: 'build'
